export const SET_EVENTS = 'SET_EVENTS';

export const TOGGLE_EVENT_CATEGORY = 'TOGGLE_EVENT_CATEGORY';

export const SET_ACTIVE_EVENT = 'SET_VIEW_EVENT';

export const LOAD_EVENTS_STARTED = 'LOAD_EVENTS_STARTED';
export const LOAD_EVENTS_FAILED = 'LOAD_EVENTS_FAILED';
export const LOAD_EVENTS_COMPLETED = 'LOAD_EVENTS_COMPLETED';
